CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY
);

INSERT INTO users VALUES (null);
INSERT INTO users VALUES (null);
INSERT INTO users VALUES (null);
INSERT INTO users VALUES (null);
INSERT INTO users VALUES (null);
INSERT INTO products VALUES (null);
INSERT INTO products VALUES (null);
INSERT INTO products VALUES (null);
INSERT INTO products VALUES (null);
INSERT INTO products VALUES (null);

