CREATE TABLE financial_reports (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    report_title VARCHAR(255) NOT NULL,
    report_content TEXT NOT NULL
);

INSERT INTO financial_reports (report_title, report_content) VALUES ('Q2 earnings report for tech companies 2023', 'This report provides an analysis of the financial performance of tech companies in the second quarter of 2023.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Annual financial report for toy industry 2022', 'Comprehensive overview of the financial status of the toy industry in 2022.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Quarterly revenue report for toy companies', 'Detailed breakdown of the revenue generated by toy companies for the past quarter.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Investment analysis for toy manufacturers', 'Insightful analysis on the investment opportunities in the toy manufacturing sector.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Profit margins of leading toy brands', 'Comparison of the profit margins of popular toy brands in the market.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Market trends in shape-shifting toys', 'Analysis of the latest market trends and consumer preferences in shape-shifting toys.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Economic impact of toy fairs', 'Study on the economic impact of toy fairs and their contribution to the industry.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Global toy sales forecast for 2024', 'Projection of global toy sales and market forecast for the upcoming year.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Toy production cost analysis', 'Detailed analysis of the production costs involved in manufacturing toys.');
INSERT INTO financial_reports (report_title, report_content) VALUES ('Environmental sustainability in toy manufacturing', 'Report on the implementation of eco-friendly practices in the toy manufacturing process.');
